n = input('Digite um valor:  ')
print('O tipo primitivo desse valor é ',type(n))
print('Possui espaços : ', n.isspace())
print('É um número: ',n.isnumeric())
print('É alfabético: ',n.isalpha())
print('É alfanumérico:',n.isalnum())
print('Esta em letras maiusculas: ', n.isupper())
print('Esta em letras minusculas: ', n.islower())
print('Esta capitalizada: ',n.istitle())
print('É decimal: ',n.isdecimal())
print('Esta na tabela ascii:',n.isascii())